name: 'Inject MomenToMoiX Drivers'
description: 'Inject MomenToMoiX drivers'

runs:
  using: 'composite'
  steps:
    - name: Enable Performance & Battery Configs for MomenToMoiX
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_ZRAM=m
          CONFIG_ZRAM_DEF_COMP_ZSTD=y
          CONFIG_ZSMALLOC=m
          CONFIG_ZSMALLOC_STAT=y
          CONFIG_LRU_GEN=y
          CONFIG_LRU_GEN_ENABLED=y
          CONFIG_LRU_GEN_STATS=n
          CONFIG_COMPACTION=y
          CONFIG_MIGRATION=y
          CONFIG_KSM=y
          CONFIG_TRANSPARENT_HUGEPAGE=y
          CONFIG_IOSCHED_BFQ=y
          CONFIG_BFQ_GROUP_IOSCHED=y
          CONFIG_MQ_IOSCHED_DEADLINE=y
          CONFIG_PREEMPT=y
          CONFIG_PSI=y
          CONFIG_PREEMPT_NONE=n
          CONFIG_PREEMPT_VOLUNTARY=n
          CONFIG_HIGH_RES_TIMERS=y
          CONFIG_TCP_FASTOPEN=y
          CONFIG_CPU_IDLE=y
          CONFIG_CPU_IDLE_GOV_MENU=y
          CONFIG_CPU_IDLE_GOV_TEO=y
          CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y
          CONFIG_PM_WAKELOCKS=y
          CONFIG_PM_WAKELOCKS_LIMIT=100
          CONFIG_PM_WAKELOCKS_GC=y
          CONFIG_SUSPEND=y
          CONFIG_DEVFREQ_GOV_PERFORMANCE=y
          CONFIG_DEVFREQ_GOV_PASSIVE=y
          CONFIG_UCLAMP_TASK=y
          CONFIG_UCLAMP_TASK_GROUP=y
          CONFIG_CMA=y
          CONFIG_DMA_CMA=y
          CONFIG_MQ_IOSCHED_KYBER=y
          CONFIG_SUSPEND_FREEZER=y
          CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
          CONFIG_ENERGY_MODEL=y
          CONFIG_SCHED_MC=y
          CONFIG_NO_HZ_IDLE=y
          CONFIG_NO_HZ_FULL=n


    - name: 'Inject MomenToMoiX Driver'
      shell: bash
      run: |
        set -euo pipefail
        TARGET_DIR="$GITHUB_WORKSPACE/kernel/common"
        mkdir -p "$TARGET_DIR/drivers/momx"
        cd "${{ github.action_path }}/patches/tenebrion"
        cp MomenToMoiX.c "$TARGET_DIR/drivers/momx/MomenToMoiX.c"
        cp Makefile "$TARGET_DIR/drivers/momx/Makefile"
        if ! grep -q "momx/" "$TARGET_DIR/drivers/Makefile"; then
          echo "obj-y += momx/" >> "$TARGET_DIR/drivers/Makefile"
        fi
  
        echo "✅ Inject MomenToMoiX Driver successfully."

    - name: 'Inject MomenToMoiX SELinux Rules'
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common/drivers/kernelsu
      run: |
        set -euo pipefail
        patch -p2 --forward < "${{ github.action_path }}/patches/tenebrion/tenebrion.patch"

        echo "✅ Inject MomenToMoiX SELinux Rules successfully."

